server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yang
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.yang.springboot.code.been

logging:
  level:
    com:
      yang:
        springboot:
          code:
            dao:debug
  path: concretepage/logs
  file: readman.log
