server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://10.211.55.9:3306/readman
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.yang.springboot.code.been

logging:
  level:
    com:
      yang:
        springboot:
          code:
            dao:debug
  path: concretepage/logs
  file: readman.log
wx:
  appsecret: 220f16d2f88e47ada57eb38f2b81867f
  appid: wxf465ec59a088a2b1
